"""new fields in user model

Revision ID: 84434ceeea80
Revises: 39bfdf893a47
Create Date: 2018-01-13 17:12:25.819602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84434ceeea80'
down_revision = '39bfdf893a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
